In [1]:
import numpy as np
a = np.array(range(3))
print(a)
print(type(a))

[0 1 2]
<class 'numpy.ndarray'>


In [2]:
 np.array(tuple(range(2)))

array([0, 1])

In [3]:
np.array([[1,  2],  [3,  4]])

array([[1, 2],
       [3, 4]])

In [4]:
 np.array({3,4})

array({3, 4}, dtype=object)

In [5]:
np.asarray(list(range(2)))

array([0, 1])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [10]:
np.linspace(3,6,3,endpoint=True)

array([3. , 4.5, 6. ])

In [11]:
 np.logspace(1.2,3,3,base=2)

array([2.29739671, 4.28709385, 8.        ])

In [12]:
a = np.random.uniform(44,90)
print(a)
print(type(a))

68.92534430692776
<class 'float'>


In [13]:
np.random.uniform(75.5, 125.5, size=(2, 2))

array([[124.66921585, 115.63781274],
       [119.37995795,  97.84941773]])

In [14]:
np.random.rand(2,3)

array([[0.9809658 , 0.04164286, 0.50893337],
       [0.07410939, 0.45753834, 0.22345627]])

In [15]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[1:6]

array([1, 2, 3, 4, 5])

In [16]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a[1:,:]

array([[3, 4, 5],
       [4, 5, 6]])

In [17]:
a[1:,...]

array([[3, 4, 5],
       [4, 5, 6]])

In [18]:
x = np.array([[1,  2],  [3,  4],  [5,  6]])
x[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [19]:
x = np.arange(1,13)
x1=x.reshape(3,4)
x1[1:2,2:3]

array([[7]])

In [20]:
x1[x1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [21]:
x1[x1%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [22]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):           #默认按照行输出
    print (x, end=", " )

0, 1, 2, 3, 4, 5, 

In [23]:
for x in np.nditer(a,order="F"):  #按列输出
    print(x,end=',')

0,3,1,4,2,5,

In [24]:
for row in a:    
    print(row)

[0 1 2]
[3 4 5]


In [25]:
for i in a.flat: #获得a的展开的一维数组
    print(i,end=',')

0,1,2,3,4,5,

In [26]:
a = np.arange(1,10).reshape(3,3)
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = np.arange(12).reshape(2,6)
print(a)
a.resize((3,4),refcheck=False)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
a=np.arange(3)
np.broadcast_to(a,(3,3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [30]:
np.broadcast_to(3,3)

array([3, 3, 3])

In [31]:
x=np.arange(3)
x.ndim

1

In [32]:
y=np.expand_dims(x,axis=0)
y.ndim

2

In [33]:
x.shape

(3,)

In [34]:
y.shape

(1, 3)

In [35]:
y

array([[0, 1, 2]])

In [36]:
a=np.arange(3)
a=np.expand_dims(a,axis=0)
a

array([[0, 1, 2]])

In [37]:
a.shape

(1, 3)

In [38]:
b=np.squeeze(a)  #降维度
b

array([0, 1, 2])

In [39]:
b.shape

(3,)

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=0)
print('a:',a)
print('b:',b)
print('c:',c)

a: [[1 2]
 [3 4]]
b: [[5 6]
 [7 8]]
c: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [43]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [44]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
a = np.array([[1,2,3],[4,5,6]])
b = np.append(a,[7,8,9])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


In [46]:
c = np.append(a,[[7,8,9]],axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
d = np.append(a,[[1,1,1],[2,2,2]],axis=1)
print(d)

[[1 2 3 1 1 1]
 [4 5 6 2 2 2]]


In [48]:
np.insert(a,3,[11,12]) #在数组a 的第三个索引位置处插入列表[11,12],没有提供插入的方向，所以默认展开为一维数组

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [49]:
np.insert(a,1,[11],axis = 0) #在数组a中行索引为1 的地方插入一行[11,11,11]

array([[ 1,  2,  3],
       [11, 11, 11],
       [ 4,  5,  6]])

In [50]:
 np.insert(a,1,11,axis = 1) #在数组a中列索引为1 的地方插入一列[11,11]

array([[ 1, 11,  2,  3],
       [ 4, 11,  5,  6]])

In [51]:
print(a)
np.delete(a,[1,2])
'''
如果输入的数组是一个多维的数组，先将数组展开，
再按照输入的整数或者整数组删除对应位置的元素

'''

[[1 2 3]
 [4 5 6]]


'\n如果输入的数组是一个多维的数组，先将数组展开，\n再按照输入的整数或者整数组删除对应位置的元素\n\n'

In [52]:
b=np.broadcast_to(3,(3,3))
c = np.unique(b,return_index = True)
print(b)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
(array([3]), array([0], dtype=int64))


In [53]:
import numpy as np
a = np.arange(3)
print(a)
print(a+4)

[0 1 2]
[4 5 6]


In [54]:
print(a+a)
print(a * a) #这里的乘法只是算术运算，不是矩阵运算

[0 2 4]
[0 1 4]


In [55]:
a = np.arange(6)
b = np.arange(6,0,-1)
print(a)
print(b)
print(a==b)

[0 1 2 3 4 5]
[6 5 4 3 2 1]
[False False False  True False False]


In [56]:
import numpy as np
f=list(filter(lambda x: not x.startswith('__'),dir(np)))
print(len(f))
print(f)

605
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'alen', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'ar

In [57]:
a = np.arange(6)
#输入的数组一定的是np.array对象，则可以直接使用np.min()，
#如果输入的数组不一定是array对象，可以使用np.amin()
np.amin(a)

0

In [58]:
#计算最大值
np.amax(a)

5

In [59]:
#计算最小值和最大值的差值
np.ptp(a)

5

In [60]:
np.percentile(a,60)

3.0

In [61]:
#数组元素的算术平均值
np.mean(a)

2.5

In [62]:
#元素的加权平均值
np.std(a)

1.707825127659933

In [63]:
#数组元素的方差
np.var(a)

2.9166666666666665

In [64]:
aa=np.random.uniform(1,5,(2,3))
print(aa)
print(np.sort(aa))

[[4.78175183 1.00868575 4.4134155 ]
 [3.70931531 1.52151298 3.63420131]]
[[1.00868575 4.4134155  4.78175183]
 [1.52151298 3.63420131 3.70931531]]


In [65]:
#返回最大值的索引
np.argmax(aa)

0

In [66]:
#返回最小值的索引
np.argmin(aa)

1

In [67]:
#返回数组aa中满足条件元素的索引
np.where(aa>2.5)

(array([0, 0, 1, 1], dtype=int64), array([0, 2, 0, 2], dtype=int64))

In [68]:
#返回满足条件的元素
np.extract(aa>2.5,aa)

array([4.78175183, 4.4134155 , 3.70931531, 3.63420131])

In [69]:
a=np.random.rand(2,3)
np.save('../pythonCourseCode/ok',a)
c=np.load('../pythonCourseCode/ok.npy')
print(c)

[[0.50202238 0.16196882 0.24861024]
 [0.30467685 0.84329706 0.7650736 ]]


In [70]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c =a*a
np.savez("ok3.npz", a, b, ok = c)
r = np.load("ok3.npz")  
print(r.files) # 查看各个数组名称
print(r["arr_0"]) # 数组 a
print(r["arr_1"]) # 数组 b
print(r["ok"]) # 数组 c

['ok', 'arr_0', 'arr_1']
[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[ 1  4  9]
 [16 25 36]]


In [71]:
a=np.random.uniform(2,6,(2,2))
np.savetxt('../pythonCourseCode/ok.txt',a,fmt='%f',delimiter=',')
np.loadtxt('ok.txt',dtype=float,delimiter=',')

array([[2.236689, 4.839663],
       [4.355465, 5.814528]])